name: Java CI with JUnit

on:
  push:
    branches:
      - main
      - feature/* # Ejecuta la acción en todas las ramas feature
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Construir el proyecto y ejecutar pruebas con Maven
    - name: Build and run tests
      run: mvn clean test