name: Java CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # O windows-latest si prefieres usar Windows

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2'  # Versión específica de Java
          distribution: 'temurin'  # Usamos 'temurin', que es la marca de OpenJDK por parte de Adoptium
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false

      - name: Change directory to project folder
        run: cd src  # Cambia 'src' por el nombre de la carpeta que contiene tu archivo pom.xml

      - name: Build with Maven
        run: mvn clean install  # Ahora Maven debería ejecutarse en el directorio correcto

      - name: Run tests
        run: mvn test
