name: Java CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install  # Ejecutar Maven sin necesidad de cambiar de directorio

      - name: Run tests
        run: mvn test  # Ejecutar las pruebas en la raíz del repositorio
