name: Java CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Usando un entorno de Windows en lugar de Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2'  # Usamos la versión de Java 22 en el entorno Windows

      - name: Build with Maven
        run: mvn clean install  # Ejecutar Maven en Windows

      - name: Run tests
        run: mvn test  # Ejecutar las pruebas en Windows
