name: Java CI/CD Workflow

on:
  push:
    branches:
      - main  # Asegúrate de que esté configurado para 'main'
  pull_request:
    branches:
      - main  # Y también para pull requests a 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2'  # Usando la versión precisa de Java
          distribution: 'temurin'  # Usamos temurin como distribución de OpenJDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
