name: Java CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2'
          distribution: 'temurin'

      - name: Change directory to the project folder
        run: cd test_netbeans_serverglassfish  # Navegar a la carpeta de tu proyecto

      - name: Build with Maven
        run: mvn clean install  # Ejecutar Maven en esa carpeta

      - name: Run tests
        run: mvn test  # Ejecutar las pruebas en esa carpeta
