name: Java CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.2' 
          distribution: 'temurin'  
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false

      - name: Change directory to project folder
        run: cd C:\Users\jorge\OneDrive\Documentos\NetBeansProjects\test_netbeans_serverglassfish\pom.xml

      - name: Build with Maven
        run: mvn clean install  

      - name: Run tests
        run: mvn test
